import { Poppins } from "next/font/google";
import "./globals.css";

import Header from "@/components/header";

const roboto = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Peach Flask",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-light`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
